### ISSUE TITLE
[Forge] Crash with newest version of Quark

### ISSUE THREAD

**Issue by FrogBirddd** [svenhjol/Charmonium#12]
[crash-2020-12-15_19.34.04-fml.txt](https://github.com/svenhjol/Charmonium/files/5699524/crash-2020-12-15_19.34.04-fml.txt)
Quark changed how its world gen works internally, causing a crash with this mod. Log says it has something to do with the big dungeons.

**Comment by FynnWaelsing** [comment]
Same here. The Quark version is Quark-r2.4-280, for clarification.

**Comment by FrogBirddd** [comment]
This just got fixed, closing the issue.
