### ISSUE TITLE
Standalone Fabric Mod

### ISSUE THREAD

**Issue by haze** [svenhjol/Charmonium#20]
Is there any way the foundation from Charm could be extracted out to have 
Charmonium function on it's own as a mod? I'd like to use this mod on a realms server which unfortunately does not allow me to install mods there.  If, however this mod requires server configuration, please feel free to close.

**Comment by svenhjol** [comment]
That would be a good idea, I'd love to make it a client-only mod. There are a couple of problems at the moment though. Charmonium depends on Charm for its music improvements module so that new tracks can play under certain conditions. This would have to be extracted as you mentioned. I'll keep it in mind as a future enhancement though.

**Comment by YumatanGames** [comment]
Well, I came here just to ask the same thing. I love Charmonium, but don't want all the things Charm adds to the game and would love to have it on its on. 👍

**Comment by PenguinsWillLickYou** [comment]
> That would be a good idea, I'd love to make it a client-only mod. There are a couple of problems at the moment though. Charmonium depends on Charm for its music improvements module so that new tracks can play under certain conditions. This would have to be extracted as you mentioned. I'll keep it in mind as a future enhancement though.

Any update on this?

**Comment by Moonflowey** [comment]
I would love this aswell. There barely are any good ambient sound mods for fabric, which kinda sucks. Charmonium has great potential to fill in that void lol

**Comment by RickyTheRacc** [comment]
Agreed, waiting on the day this becomes a standalone mod

**Comment by svenhjol** [comment]
It's being built right now :)  You can track progress on this branch. https://github.com/svenhjol/Charmonium/tree/client-only

**Comment by svenhjol** [comment]
It's ready. https://www.curseforge.com/minecraft/mc-mods/charmonium/files/3379114

**Comment by haze** [comment]
Elite!

**Comment by Yummatan** [comment]
Amazing! I love your mods, btw. Thank you!

**Comment by GaimGoddes** [comment]
> It's ready. https://www.curseforge.com/minecraft/mc-mods/charmonium/files/3379114

Heyo, I know I'm very late to this conversation. I'd love to use charmonium for all its pretty sounds, but due to the server I frequent, I'm stuck in 1.16 until it updates. It would be awesome if you could backport the stand-alone Charmonium to older versions!
