### ISSUE TITLE
How do you build the 1.18 branch?

### ISSUE THREAD

**Issue by Plastogerm** [svenhjol/Charmonium#36]
Hello!

I've downloaded the [1.18 branch](https://github.com/svenhjol/Charmonium/tree/1.18.x) and extracted it, opened the Windows command prompt and navigated to the folder and typed in `gradlew build`
Everytime I try to do this, the code runs for some time, but then displays a failure message, saying that it has 'Failed to get intermediary'.

![image](https://user-images.githubusercontent.com/35829165/152113792-24681224-2364-4d05-95d5-a82cd9c6e1a4.png)

Can someone please help me resolve this? I'm new to doing these, so I'm sorry if I've missed an obvious step.

**Comment by Icelk** [comment]
Works for me.
Have you built Charm and put it in `./lib/charm.jar`?
That seemed to work for me.

**Comment by Plastogerm** [comment]
> Works for me. Have you built Charm and put it in `./lib/charm.jar`? That seemed to work for me.

Nope. I haven't even built it at all, it just keeps returning that same error message for me unfortunately.

Could you please send me your build instead Icelk? I'd appreciate it so, very much.

**Comment by Icelk** [comment]
Here you go:
https://icelk.dev/rsync-ignore/charmonium-fabric-1.18-4.0.0.jar

That was built using the latest commit.

**Comment by Plastogerm** [comment]
> Here you go: https://icelk.dev/rsync-ignore/charmonium-fabric-1.18-4.0.0.jar
> 
> That was built using the latest commit.

I'll be closing this now. Maybe it's just a really weird, one-off issue that only happens on my machine, as I can't seem to build any _other_ mods either.

But I appreciate this a lot, thank you so much! :hugs:
