### ISSUE TITLE
[Suggestion] A way where we can have charmonium installed without having to have charm

### ISSUE THREAD

**Issue by WitheredWasabi** [svenhjol/Charmonium#9]
I love Charmonium and the atmosphere it brings to Minecraft, but Charm is not my style of mod to play with, so I really hope you take this suggestion into consideration, and sorry if this wasn't the best place to ask

**Comment by Coranthes** [comment]
You can set all the enabled Charm features to false, which will disable everything while still allowing you to play with Charmonium.

**Comment by WitheredWasabi** [comment]
Yeah, I know I can but doing it that way just seems counterintuitive.

**Comment by svenhjol** [comment]
The Charm mod provides a foundation of sorts for Charmonium (and the upcoming mod Strange) to function without having to rewrite a bunch of code and changes, so the only thing we can offer is to disable all Charm modules.
